STRIPE_PUBLIC_KEY: STRIPE PUBLIC KEY
STRIPE_SECRET_KEY: STRIPE SECRET KEY

baseURL: https://infallible-swartz-b50174.netlify.app

logging:
  level:
    org:
      hibernate:
        SQL: debug
security:
  require-ssl: true

server:
  port: 8443
  servlet:
    contextPath: /api
#  ssl:
#    key-store: /etc/letsencrypt/live/remotedevs.org/keystore.p12
#    key-store-password: password
#    keyAlias: tomcat
#    keyStoreType: PKCS12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: ALWAYS
    username: fashionavid
    password: fashionavid
    url: jdbc:mysql://localhost/ecommerce-dev

  jpa:
    hibernate:
      ddl-auto: update
#    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true